### PR TITLE
MD Monitor commands with faulty dumpcram.

### PR DESCRIPTION
**Pull request by MintyTheCat**
Hi Chris,

sorry, it took me a while to work out what Git was doing.

We have a few commands added here that are mostly VDP related.
I have also cleaned things up a bit and added the md_vdp files.

At this time it is very messy and needs to be improved but it is a start.

I will be looking into why dump CRAM fails.

### CODE REVIEW

**Comment by makestuff** [comment]
Thanks for the patch! Unfortunately it will need some more work before I can merge it.

The most obvious problem is the target branch - all development work should go into the **dev** branch. The only way stuff gets into the **master** branch is when I cut a release, I merge **dev** into **master**, apply the release label and write the [change-list](https://gist.github.com/makestuff/9875167#20151220). That way, **master** always points at the most recent release.

There are also quite a lot of stylistic problems:
   * Braces should use the [K&R style](https://en.wikipedia.org/wiki/Indent_style#Variant:_1TBS).
   * Enum values should be in UNDERSCORED_UPPER_CASE.
   * Enum types should be typedeffed and in UpperCamelCase.
   * Structs should not be typedeffed and in UpperCamelCase.
   * Variables and function-names should be in lowerCamelCase.

Try to keep spacing consistent with the rest of the projects:
   * Do "for ( i = 0; i < 16; i++ )" rather than "for(i=0;i<16;i++)".
   * Tabs should only occur at the start of a line, never in the middle.

This list is probably not exhaustive. Just look at the rest of the [makestuff](https://github.com/makestuff?tab=repositories) code to get an idea of conventions. If you want to change a stylistic policy, we can discuss it, but any policy change would then have to be applied globally across all ~50 or so repos, so the reason has to be quite compelling.

Some implementation problems:
   * Structure bitfields are nonportable and should probably not be used, but if you insist there should be conditional compilation for BYTE_ORDER=1234 (e.g Intel) and for BYTE_ORDER=4321 (e.g PowerPC).
   * The [UGB_VDP_VDPStatus()](https://github.com/MintyTheCat/umdkv2/blob/master/gdb-bridge/md_vdp.c#L99) function accepts a statStrMaxLen argument (which should be of type size_t, BTW) but then ignores it by using strcat().
   * There are lots of TODOs, some suggesting the CRAM-readback bug still exists. I'm not too happy about committing code that has known bugs in it.

Finally a word on comments:
   * There's no point having detailed change-logs, dates and author annotations in comments - that's what Git is for. Similarly, committing commented-out code is a Bad Idea (though I admit to doing it myself sometimes).
   * Detailed documentation covering the purpose of a function, its arguments are return-value is OK but it's better to use a machine-readable format like Doxygen. For example, [this header](https://github.com/makestuff/libfpgalink/blob/20140524/libfpgalink.h) contains Doxygen annotations that generate [this API-doc](http://www.swaton.ukfsn.org/bin/fpgalink-20140524/c/libfpgalink_8h.html)  and [this cleaned-up header](http://www.swaton.ukfsn.org/bin/fpgalink-20140524/c/libfpgalink_8h_source.html) (for people who prefer to read code without the comment-clutter).

Sorry for all these nit-picks, but I think it's important to maintain a consistent style across the project.

**Comment by MintyTheCat** [comment]
No worries, Chris.

I shall go through the source and ensure that it matches.

Also, Git is all a bit new to me so I have not gotten to grips with it 
as yet but it makes perfect sense to submit in the dev tree.


On 24/01/16 17:48, Chris McClelland wrote:
>
> Thanks for the patch! Unfortunately it will need some more work before 
> I can merge it.
>
> The most obvious problem is the target branch - all development work 
> should go into the *dev* branch. The only way stuff gets into the 
> *master* branch is when I cut a release, I merge *dev* into *master*, 
> apply the release label and write the change-list 
> <https://gist.github.com/makestuff/9875167#20151220>. That way, 
> *master* always points at the most recent release.
>
> There are also quite a lot of stylistic problems:
>
>   * Braces should use the K&R style
>     <https://en.wikipedia.org/wiki/Indent_style#Variant:_1TBS>.
>   * Enum values should be in UNDERSCORED_UPPER_CASE.
>   * Enum types should be typedeffed and in UpperCamelCase.
>   * Structs should not be typedeffed and in UpperCamelCase.
>   * Variables and function-names should be in lowerCamelCase.
>

I have never liked the K&R brace style but I shall ask astyle to make it 
look as it needs to.
>
> Try to keep spacing consistent with the rest of the projects:
>
>   * Do "for ( i = 0; i < 16; i++ )" rather than "for(i=0;i<16;i++)".
>   * Tabs should only occur at the start of a line, never in the middle.
>
> This list is probably not exhaustive. Just look at the rest of the 
> makestuff <https://github.com/makestuff?tab=repositories> code to get 
> an idea of conventions. If you want to change a stylistic policy, we 
> can discuss it, but any policy change would then have to be applied 
> globally across all ~50 or so repos, so the reason has to be quite 
> compelling.
>
Completely understandable.  I will sort it out.  I only cleaned things 
up a bit before passing you the commands.  The CRAM dump issue has taken 
my focus.
>
> Some implementation problems:
>
>   * Structure bitfields are nonportable and should probably not be
>     used, but if you insist there should be conditional compilation
>     for BYTE_ORDER=1234 (e.g Intel) and for BYTE_ORDER=4321 (e.g PowerPC).
>   * The UGB_VDP_VDPStatus()
>     <https://github.com/MintyTheCat/umdkv2/blob/master/gdb-bridge/md_vdp.c#L99>
>     function accepts a statStrMaxLen argument (which should be of type
>     size_t, BTW) but then ignores it by using strcat().
>   * There are lots of TODOs, some suggesting the CRAM-readback bug
>     still exists. I'm not too happy about committing code that has
>     known bugs in it.
>
Yes, bitfields are naughty.  I can easily use unsigned Bytes or Words 
and simply mask them off.
Indeed, this is ropey; I shall alter this for a strncat.

CRAM readback most certainly is still an issue.  I have only passed it 
in as a stopgap.  Indeed, dev is the better place.

We shall leave it for now until I have spent some time working out why 
CRAM dumps fail - the traces.  Then I will sort the files out and make 
them conform.
>
> Finally a word on comments:
>
>   * There's no point having detailed change-logs, dates and author
>     annotations in comments - that's what Git is for. Similarly,
>     committing commented-out code is a Bad Idea (though I admit to
>     doing it myself sometimes).
>   * Detailed documentation covering the purpose of a function, its
>     arguments are return-value is OK but it's better to use a
>     machine-readable format like Doxygen. For example, this header
>     <https://github.com/makestuff/libfpgalink/blob/20140524/libfpgalink.h>
>     contains Doxygen annotations that generate this API-doc
>     <http://www.swaton.ukfsn.org/bin/fpgalink-20140524/c/libfpgalink_8h.html>
>     and this cleaned-up header
>     <http://www.swaton.ukfsn.org/bin/fpgalink-20140524/c/libfpgalink_8h_source.html>
>     (for people who prefer to read code without the comment-clutter).
>
Yes, it is not working, tbh I was going on what you stated when you said 
to submit a simple set of changes first.  All of this is not complete 
and I am not happy with any of it as yet.

I did not realise that UMDK used Doxygen.  I use it in my own projects 
and I like it.  Let's support Doxygen instead.  I did not see any tags 
in your code but tbh I did not do any real searching either.
>
> Sorry for all these nit-picks, but I think it's important to maintain 
> a consistent style across the project.
>
No worries at all, it needs to be up to standard either way.

I really just wanted to show you the issues that dump CRAM has and given 
that I am still on the Debian 8 VM (will be leaving this once my NAS' 
SVN issue is resolved) I will be moving onto a physical Debian 8 
installed machine for my UMDK work.

Give me a bit of time to sort this out and to send patches to the 
correct tree.

Cheers,

Chris.

**Comment by makestuff** [comment]
> I did not realise that UMDK used Doxygen.  I use it in my own projects
> and I like it.  Let's support Doxygen instead.  I did not see any tags
> in your code but tbh I did not do any real searching either.

It doesn't, currently. But the underlying makestuff libraries (libfpgalink, libusbwrap, libfx2loader, libbuffer, etc) all do, and if we're going to start adding doc annotations to every function, we should stick to a recognised format, that's all.

> ...until I have spent some time working out why
> CRAM dumps fail - the traces

I wonder if [this](https://github.com/makestuff/umdkv2/pull/6/files#diff-d6cb77dc80e0294b9397842feeb546e6R351) is causing problems? You know that under the covers, umdkWriteLong() ultimately results in two separate **move.w** instructions on two separate [loop iterations](https://github.com/makestuff/umdkv2/blob/20151220/gdb-bridge/monitor/monitor.s#L175-L183), right? Won't the VDP be expecting the two contiguous writes that normally result from a **move.l** instruction?

Thinking about this some more, there's a rough distinction currently between the low-level functions (for reading and writing memory and issuing commands to the monitor) which are all named "umdkXXX()", and the higher-level functions that implement the GDB protocol. Ideally, the low-level functions should be factored out into a static library with an independent test-suite. Anyway, it would be good to maintain this separation for reading VDP state and CRAM. You could then write some integration tests (e.g [testMem.cpp](https://github.com/makestuff/umdkv2/blob/20151220/gdb-bridge/tests/testMem.cpp)) which run on real hardware, so you can get the low-level functionality working in isolation without worrying about whether there's a bug in the higher-level GDB code.

**Comment by MintyTheCat** [comment]
On 24/01/16 19:39, Chris McClelland wrote:
>
>     I did not realise that UMDK used Doxygen. I use it in my own projects
>     and I like it. Let's support Doxygen instead. I did not see any tags
>     in your code but tbh I did not do any real searching either.
>
> It doesn't, currently. But the underlying makestuff libraries 
> (libfpgalink, libusbwrap, libfx2loader, libbuffer, etc) all do, and if 
> we're going to start adding doc annotations to every function, we 
> should stick to a recognised format, that's all.
>
No worries.
>
>     ...until I have spent some time working out why
>     CRAM dumps fail - the traces
>
> I wonder if this 
> <https://github.com/makestuff/umdkv2/pull/6/files#diff-d6cb77dc80e0294b9397842feeb546e6R351> 
> is causing problems? You know that under the covers, umdkWriteLong() 
> ultimately results in two separate *move.w* instructions on two 
> separate loop iterations 
> <https://github.com/makestuff/umdkv2/blob/20151220/gdb-bridge/monitor/monitor.s#L175-L183>, 
> right? Won't the VDP be expecting the two contiguous writes that 
> normally result from a *move.l* instruction?
>
No, this is standard practice: two Word writes is the same as one Long 
write as far as the VDP is concerned.  If it there is a duration between 
W1 and W2 write, and implicitly due to internal loading there is one 
anyway even with a Long write there is no difference.  So If the VDP 
never gets W2 having gotten W1 it will sit forever and never latch the 
Word out when we do a read on the data port.  It is pretty simple as 
chips go I feel.

I shall put together a ROM to prove this but I am pretty certain having 
used the MD as long as I have now.
>
> Thinking about this some more, there's a rough distinction currently 
> between the low-level functions (for reading and writing memory and 
> issuing commands to the monitor) which are all named "umdkXXX()", and 
> the higher-level functions that implement the GDB protocol. Ideally, 
> the low-level functions should be factored out into a static library 
> with an independent test-suite. Anyway, it would be good to maintain 
> this separation for reading VDP state and CRAM. You could then write 
> some integration tests (e.g testMem.cpp 
> <https://github.com/makestuff/umdkv2/blob/20151220/gdb-bridge/tests/testMem.cpp>) 
> which run on real hardware, so you can get the low-level functionality 
> working in isolation without worrying about whether there's a bug in 
> the higher-level GDB code.
>
This makes perfect and good sense: integration tests are a very good 
idea.  I was impressed that you added in many HW tests during testing 
and this is the way to go and saves potentially a great deal of support 
related issues that Users will no doubt raise down the line.

I just need to prove that what the VDP sees in terms of writes and the 
resultant latched Word on the data port read are correct so a low-level 
test is a good first step.
Either way, the trace will show me what the VDP sees.  It just has 
confounded me as the method should be sound - famous last words and all 
that :)

I agree entirely that having the system as robust is exactly the way to 
go for UMDK.  It is meant to be a long-term project and not a 
five-minute, quick wonder.  Also, the more reliable it is the more 
likely people will trust it over time.
I have not released MD Util 2 because it would a) require me to write a 
test-harness that I have not done as yet and b) I have no time to 
support the type of questions Users of MDU2 will be asking. I see how 
much effort is required to support SGDK and UMDK and I just do not have 
the time for it now but I shall release it once I have gotten to where I 
need to be for the Shmup project.

**Pull request closed without merging**
