### PR TITLE
Patch: Small monitor optimization

### PR DESCRIPTION
**Pull request by radexx**
This patch contains the ammendments discussed in our previous conversation.

Please compile it before merging and let me know if you see anything wrong.

Cheers

### CODE REVIEW

**Comment by makestuff** [comment]
Thanks. I'll try this out (perhaps at the weekend) before I merge it.

**Comment by makestuff** [comment]
OK I tried this and it works OK. A couple of small problems: (1) your comment "14 32-bit registers" in monitor.s is wrong, it should be "15 32-bit registers", and (2) if you run "make" in the monitor directory with your version of monitor.s it tells you the monitor reset address is 0x4000dc and asks you to ensure that the reset address in ddd.sh is the same. It isn't the same, so you'll need to edit scripts/ddd.sh to replace 0x400180 with 0x4000dc. Your PR should update automatically, and then I can merge it.

**Comment by makestuff** [comment]
Awesome work, thanks!

**Comment by radexx** [comment]
All fixed, thank you for the traces. Nice 2x+ speedup!!

**Pull request merged**
